# left-side user profile
avatar: https://ja.gravatar.com/userimage/58582291/557bcfb812bf7e8083f2346de7d70334.jpg?size=10000
location:
email: leojojo@sfc.wide.ad.jp
social:
  github: https://github.com/leojojo
  twitter: https://twitter.com/meganepikumin

# navbar menu
menu:
 archives: false
 tags: true
 categories: true

rss_dir: atom.xml

# widget
ga: UA-105154164-2
